export const URL = 'URL';
// Authentication
export const AUTHENTICATE = 'AUTHENTICATE';
export const DEAUTHENTICATE = 'DEAUTHENTICATE';
// Nav
export const HOMETAB = 'HOMETAB';
export const GFTAB = 'GFTAB';
export const SGATAB = 'SGATAB';
export const RESULTAB = 'RESULTAB';
export const MEDIATAB = 'MEDIATAB';
export const JUGESTAB = 'JUGESTAB';
// Content
export const HOMECONTENT = 'HOMECONTENT';
export const SGACONTENT = 'SGACONTENT';
export const GFCONTENT = 'GFCONTENT';
export const JUGESCONTENT = 'JUGESCONTENT';
export const CURRENTACTU = 'CURRENTACTU';
export const GALERIECONTENT = 'GALERIECONTENT';
export const CURRENTRESULT = 'CURRENTRESULT';
export const VIDPLAYCONTENT = 'VIDPLAYCONTENT';
export const MEDIATHEQUECONTENT = 'MEDIATHEQUECONTENT';
export const CALENDARCONTENT = 'CALENDARCONTENT';
export const RESULTSBOXCONTENT = 'RESULTSBOXCONTENT';